### ISSUE TITLE
bactdating is not compatible with R 3.6.0 

### ISSUE THREAD

**Issue by happykhan** [xavierdidelot/BactDating#14]
package 'BactDating' is not available (for R version 3.6.0) 

this is when I fetch from CRAN,

**Comment by xavierdidelot** [comment]
Hi Nabil,

I think this happened because you tried installing BactDating with a standard command such as:
install.packages('BactDating')

However, the command above only works for packages that are on CRAN. Since BactDating is not on CRAN (at least yet) you need to install it using the command:
devtools::install_github("xavierdidelot/BactDating")

This might require to first install the devtools package using:
install.packages('devtools')

Best wishes,
Xavier
