### ISSUE TITLE
res$tree$root.time different from root date in print(res)

### ISSUE THREAD

**Issue by fengyuchengdu** [xavierdidelot/BactDating#17]
Dear Xavier,

1) Is that normal these two values are different?

2) Should I use "useRec = T" to run bactdate when loading from gubbins?

Thanks,

Yu

**Comment by xavierdidelot** [comment]
Hi Yu,

1. yes, this happens because res$tree$root.time is the mean when the root is on the branch shown in res$tree whereas in print(res) the root date is the mean when the root could be on any branch.

2. yes you should.

Best wishes,
Xavier

**Comment by nbawe** [comment]
Which one to is better to report - print(res) root time? I know the issue is closed, but when exporting tree to nex format and displaying node labels what's the difference in
1) length_0.95_HPD
2) height_0.95_HPD?

And how to calculate years from them?

**Comment by xavierdidelot** [comment]
I would say it is usually better to report the dates for the most likely root, which is what you get from `res$tree$root.time` and the credible interval is given by `res$CI[Ntip(res$tree)+1,]`

To make this simpler to report and avoid further confusion, I have just added a new line at the end of `print(res)` which contains these values. 

I think it is better to report these dates because they are the ones shown in the dated phylogeny from `plot(res,'tree')` and/or `plot(res,'treeCI')` 

There would usually not be too much difference anyway between these values conditioned on most likely root and the unconditioned dates. If you want to be really thorough you could report both.

`length_0.95_HPD` and `height_0.95_HPD` are essentially the same intervals measured differently, as needed for compatibility with ggtree.
