### ISSUE TITLE
Strength of temporal signal!

### ISSUE THREAD

**Issue by nbawe** [xavierdidelot/BactDating#18]
> Before running the main `bactdate` analysis, it is also a good idea
> to assess the strength of the temporal signal using a root-to-tip linear regression

How would you assess it with p-value? 

Is it significant with results as follows:

Rate=3.77e+01,MRCA=1973.70,R2=0.15,p<1.00e-04

<img width="436" alt="Screenshot 2019-11-09 at 02 13 05" src="https://user-images.githubusercontent.com/33641382/68519156-fd3a6000-0297-11ea-8235-b1d1f12d7ce7.png">

Additional info:
I am using RAxML bipartition tree with branch labels as input rescaled using total lenght of 130 recombination free core alignment approx 1.2Mbp (eg 1200000) sites and then rooted as described in vinegettes.

**Comment by nbawe** [comment]
Also ran CFML and BactDating with following result to root to tip:

Rate=1.52e+01,MRCA=1969.24,R2=0.10,p<2.10e-03

<img width="433" alt="Screenshot 2019-11-09 at 13 02 52" src="https://user-images.githubusercontent.com/33641382/68527618-803bd480-02f1-11ea-96d5-86a9a57c59c7.png">

Could you help which is better?

**Comment by xavierdidelot** [comment]
Hello, 

So it seems that you get a better correlation (both R2 and p-value) before correcting for recombination which a bit disappointing. On the other hand, the rate before correction is 37.7 substitutions per year which seems too high, depending on which bacterial species you're working on. The rate after correction is 15.2 substitutions per year which is more reasonable (again it depends on the species you are working on, you should check in the literature if previously published estimates of the clock rate are in agreement). 

One thing you should check is whether your tree is correctly rooted (both before and after recombination analysis). If not, the roottotip output is meaningless. You can use the initRoot function to find the best location of the root in both case.

The other thing to do is to run bactdate and see what happens, since the roottotip analysis is only a rough way to test for the temporal signal (because tips are not actually independent, and the molecular clock might be relaxed)

Best wishes,
Xavier

**Comment by nbawe** [comment]
Before analysis I ran initRoot and used this tree to generate roottotip. What do you mean by after recombination analysis?

**Comment by xavierdidelot** [comment]
By "after recombination analysis" I mean using the ClonalFrameML tree.
By "before recombination analysis" I mean using the raxml tree.
It's fine if you say you used initRoot before running roottotip, I just wanted to check.
I think you should now try bactdate and see what happens!

**Comment by nbawe** [comment]
So I shoud use RAxML tree for root to tip or ClonalFrameML tree?

**Comment by xavierdidelot** [comment]
You should use the CFML tree for everything, unless you have good reasons to believe that CFML did not work well.

**Comment by nbawe** [comment]
Is there some kind of package or values to check to assess CFML results like in BactDating using the coda library?

**Comment by xavierdidelot** [comment]
No, the question for CFML is not whether it converged or not, but whether the results are biologically meaningful or not.

**Comment by nbawe** [comment]
Thank you!
