### ISSUE TITLE
Root-to-tip R2 value?

### ISSUE THREAD

**Issue by nbawe** [xavierdidelot/BactDating#32]
I have question. Is it ok to use results when R2 value is small (0.12), but the p-value is significant?

I have also tested temporal signal significance using equal dates with same model and also random dates permutations with multiple runs. All the analysis indicates significant temporal signal.

Thank you

**Comment by xavierdidelot** [comment]
Neither a high values of R2 nor a significant p-value are really strong evidence, because the root-to-tip approach is very rough due to the fact that root-to-tip distances are not independent of one another.

The best test in my opinion is to make sure you get a larger clock rate in your analysis than in any analysis where the dates are permuted. Or even better, make sure that the 95% credible interval with correct dates does not overlap with any of the 95% credible intervals with permuted dates. For more information see:

Duchêne, S., Duchêne, D., Holmes, E. C., and Ho, S. Y. W. 2015. The performance of the date-randomization test in phylogenetic analyses of time-structured virus data. Molecular Biology and Evolution 32:1895–1906.

**Comment by nbawe** [comment]
Hello again!

What do you mean any of the CI95%? - Do you mean only check mu values CI95% overlapping and greater than permuted dates should be in original run? 

Or should I check all values (likelihood, prior etc) CI95% overlapping?

Thank you!

**Comment by xavierdidelot** [comment]
I meant the 95% credible interval for just the substitution rate mu.

**Comment by nbawe** [comment]
Thank you for prompt answer and also for the publication you shared!
