### ISSUE TITLE
Help wanted: how to inerpret mu?

### ISSUE THREAD

**Issue by nbawe** [xavierdidelot/BactDating#33]
I have extracted C. jejuni core genome with total length ~1000000bp then ran CFML followed by BactDating, my question is how to interpret mu correctly to get per site per year value?

1) calculate per site: 
mu/(size of core genome eg the size that analysis was based on ~1000000bp)?

or

2) calculate per site: 
mu/(known genome length eg   ~1650000bp)?

Thank you!

**Comment by xavierdidelot** [comment]
Note that the CFML output tree has branch lengths measured in units of substitutions per site whereas the BactDating input file needs to have branch lengths measured in units of substitutions per genome. So you will need to multiply the branch lengths of your CFML output tree by 1e6 before you use it as input in CFML, which you can do using something like:
`tree$edge.length=tree$edge.length*1e6`
The mu estimated by BactDating will then be in units of substitutions per genome, or more precisely per core genome in your case, ie it will represent how many sbustitutions happen per year throughout the core genome. You should not try to extrapolate for the non-core, since the rates could be different there than in the core.

**Comment by nbawe** [comment]
I ran CFML and loaded results to BactDating using loadCFML() - Do I still need to multiply branch lengths or is it taken care with the loadCFML() automatically?

What is mu when I did not multiply?

Can I use mu/(core genome length) to get per site per year?

**Comment by xavierdidelot** [comment]
If you used loadCFML then there is no need to scale the branch lengths as this is done automatically for you.
So the mu you obtained was already measured in substitutions per genome per year.
Yes you can divide by the length of the core genome to obtain a result per site per year.

**Comment by nbawe** [comment]
Thank you!
