### ISSUE TITLE
calculation of mutation rate and DIC value

### ISSUE THREAD

**Issue by LeonardosMageiros** [xavierdidelot/BactDating#49]
Hi, 

Running bactdating on ~1500 S aureus strains and printing the result gives me the following:
Rooted; includes branch lengths.
Probability of root branch=0.82
likelihood=-7.83e+03 [-7.90e+03;-7.75e+03]
prior=-1.28e+04 [-1.30e+04;-1.27e+04]
mu=1.91e+00 [1.67e+00;2.15e+00]
sigma=1.59e+01 [1.41e+01;1.76e+01]
alpha=5.97e+03 [5.14e+03;6.94e+03]
Root date=-503.78 [-908.13;-148.30]
Root date for most likely root=-532.65 [-911.61;-203.64]

Can I ask what are the units of mu how I can calculate the mutation rate (per year) from the mu value? 

Can I also ask how can I interpret sigma, alpha and DIC values? 
Should I be alarmed that my DIC value is 20878.84? Is that too high?  

Thank you in advance for your help, 
Leonardos

**Comment by xavierdidelot** [comment]
Hi Leonardos,

mu is in substitutions per year.

sigma is harder to interpret and depends on the model used, but the larger the sigma the more relaxed the clock. I would not usual report this value other than to say that the clock used is a relaxed clock. Here it seems you are using the new ARC model which it would be good to mention. The paper on the ARC model which explains exactly what sigma is: 
Didelot, X., Siveroni, I., and Volz, E. M. 2021. Additive uncorrelated relaxed clock models for the dating of genomic epidemiology phylogenies. Molecular Biology and Evolution 38:307–317.

alpha is the effective population size, which is not especially interesting to report since it is reflected directly in the root date.

A high DIC value does not mean much by itself, the actual value is only meaningful if compared with other DIC values for the same dataset, for example using a strict clock model.

Best wishes,
Xavier

**Comment by LeonardosMageiros** [comment]
Xavier thank you very much once again. 

Just to be 100% sure mu is measured in substitutions per megabase per year, correct?

Thx

**Comment by xavierdidelot** [comment]
No, mu is in substitutions per year for the whole genome.
If you want it per year per bp you should divide by your genome length.
