### ISSUE TITLE
Question–– model selection with pstrict vs. other criteria? 

### ISSUE THREAD

**Issue by amyecampbell** [xavierdidelot/BactDating#69]
Hello!

I tested strictgamma, mixedgamma, and arc on my dataset, which had a good linear root-to-tip fit, using a fixed root (known based on larger phylogenetic analysis of this clade). For example, I called:

 _bactdate(tree ,dateinfo_bact,nbIts=1e8, model="mixedgamma",showProgress = T, updateRoot = F)_

All the ESS values were high as shown in the table (I used default thinning), and then DIC was lowest for strict gamma by more than the DIC difference between arc and mixedgamma. However, the pstrict for the mixedgamma result was 0. I'm wondering if you have any thoughts on how I should move forward given that? 

Thank you very much for this tool. Any thoughts you have would be appreciated.

<img width="607" alt="Screenshot 2024-05-21 at 2 03 25 PM" src="https://github.com/xavierdidelot/BactDating/assets/19710605/0c9c4561-aa51-47b6-b356-6d4c9e6f6ecf">

**Comment by xavierdidelot** [comment]
If pstrict in mixedgamma is zero then it means that relaxing the clock helps explain the data.
If you want a DIC-based equivalent of this then you should compare the DIC for the strictgamma and relaxedgamma models, since the mixedgamma model is a mix of these two models.
It is probably best to avoid comparing continuous models (like strictgamma, relaxedgamma and mixedgamma) with discrete models (like arc). 
The continuous equivalent of arc is called carc.
The discrete equivalents of strictgamma and mixedgamma are poisson and negbin, respectively.

**Comment by amyecampbell** [comment]
Thank you!
